const TRANSACTION_TYPE_INCOME = 1;
const TRANSACTION_TYPE_EXPENSE = 2;
const TRANSACTION_TYPE_TRANSFER_OUT = 3;
const TRANSACTION_TYPE_TRANSFER_IN = 4;

module.exports = {
    TRANSACTION_TYPE_INCOME,
    TRANSACTION_TYPE_EXPENSE,
    TRANSACTION_TYPE_TRANSFER_OUT,
    TRANSACTION_TYPE_TRANSFER_IN,
};
